### ISSUE TITLE
Align FSO to SAREF

### ISSUE THREAD

**Issue by alikucukavci** [alikucukavci/FSO#6]

**Comment by alikucukavci** [comment]
In overview of classes, introduction and turtle file writing that it is aligned with SAREF

**Comment by vijoc** [comment]
My thinking here is that, essentially, [SAREF4BLDG](https://saref.etsi.org/saref4bldg/latest/saref4bldg.html) includes the IFC component classes from ifcOWL, which we more or less duplicate currently. We could explicitly use those.

Additionally, [SAREF4SYST](https://saref.etsi.org/saref4syst/latest/saref4syst.html) introduces systems and connections, similar to SEAS. An important difference is that, in my understanding, SAREF4SYST does not require a system to have only one supersystem, unlike SEAS. This allows overlapping logical systems, which have been discussed in the past.

I'll look into updating the ontology and documentation, hopefully early next week.
